# Generated by Django 5.2.17 on 2026-09-13 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, max_length=120)),
                ('source_text', models.TextField()),
                ('extracted_record', models.JSONField()),
                ('missing_fields', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summarization_failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
