# Generated by Django 5.2.17 on 2026-09-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='error_category',
            field=models.CharField(blank=True, choices=[('missing_field', 'Missing field'), ('incorrect_value', 'Incorrect value'), ('hallucination', 'Hallucinated content'), ('formatting', 'Formatting / structure issue'), ('other', 'Other')], max_length=32, null=True),
        ),
    ]
