# Generated by Django 5.2.6 on 2026-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='recommendation_grounded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='recommendation_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='recommendation_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
