# Generated by Django 5.2.17 on 2026-09-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_intake', '0002_chatsession_recommendation_grounded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
